export const sr = {
  accept: "Da",
  addRule: "Dodaj pravilo",
  am: "AM",
  apply: "Primeni",
  cancel: "Odustani",
  choose: "Odaberi",
  chooseDate: "Odaberi datum",
  chooseMonth: "Odaberi mesec",
  chooseYear: "Odaberi godinu",
  clear: "Očisti",
  completed: "Završeno",
  contains: "Sadrži",
  custom: "Prilagođeno",
  dateAfter: "Datum je posle",
  dateBefore: "Datum je pre",
  dateFormat: "dd.mm.yy.",
  dateIs: "Datum je",
  dateIsNot: "Datum nije",
  dayNames: [
    "Nedelja",
    "Ponedeljak",
    "Utorak",
    "Sreda",
    "Četvrtak",
    "Petak",
    "Subota",
  ],
  dayNamesMin: ["Ned", "Pon", "Uto", "Sri", "Čet", "Pet", "Sub"],
  dayNamesShort: ["Ned", "Pon", "Uto", "Sri", "Čet", "Pet", "Sub"],
  emptyFilterMessage: "Nema pronađenih rezultata",
  emptyMessage: "Nema dostupnih opcija",
  emptySearchMessage: "Nema pronađenih rezultata",
  emptySelectionMessage: "Nema odabrane stavke",
  endsWith: "Završava sa",
  equals: "Jednako",
  fileChosenMessage: "{0} datoteka",
  fileSizeTypes: ["B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"],
  filter: "Filter",
  firstDayOfWeek: 1,
  gt: "Veće od",
  gte: "Veće ili jednako",
  lt: "Manje od",
  lte: "Manje ili jednako",
  matchAll: "Podudara se sve",
  matchAny: "Podudara se bilo koji",
  medium: "Srednje",
  monthNames: [
    "Januar",
    "Februar",
    "Mart",
    "April",
    "Maj",
    "Jun",
    "Jul",
    "Avgust",
    "Septembar",
    "Oktobar",
    "Novembar",
    "Decembar",
  ],
  monthNamesShort: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "Maj",
    "Jun",
    "Jul",
    "Avg",
    "Sep",
    "Okt",
    "Nov",
    "Dec",
  ],
  nextDecade: "Sledeća dekada",
  nextHour: "Sledeći sat",
  nextMinute: "Sledeća minuta",
  nextMonth: "Sledeći mesec",
  nextSecond: "Sledeća sekunda",
  nextYear: "Sledeća godina",
  noFileChosenMessage: "Nije odabrana datoteka",
  noFilter: "Bez filtera",
  notContains: "Ne sadrži",
  notEquals: "Nije jednako",
  now: "Sada",
  passwordPrompt: "Unesite lozinku",
  pending: "U toku",
  pm: "PM",
  prevDecade: "Prethodna dekada",
  prevHour: "Prethodni sat",
  prevMinute: "Prethodna minuta",
  prevMonth: "Prethodni mesec",
  prevSecond: "Prethodna sekunda",
  prevYear: "Prethodna godina",
  reject: "Ne",
  removeRule: "Ukloni pravilo",
  searchMessage: "Dostupno rezultata: {0}",
  selectionMessage: "Odabrano stavki: {0}",
  showMonthAfterYear: false,
  startsWith: "Počinje sa",
  strong: "Jako",
  today: "Danas",
  upload: "Učitaj",
  weak: "Slabo",
  weekHeader: "Ned",
  aria: {
    cancelEdit: "Odustani od uređivanja",
    close: "Zatvori",
    collapseLabel: "Kolaps",
    collapseRow: "Red skupljen",
    editRow: "Uredi red",
    expandLabel: "Proširiti",
    expandRow: "Red proširen",
    falseLabel: "Ne",
    filterConstraint: "Ograničenje filtra",
    filterOperator: "Operator filtera",
    firstPageLabel: "Prva stranica",
    gridView: "Prikaz u mreži",
    hideFilterMenu: "Sakrij meni filtra",
    jumpToPageDropdownLabel: "Skok na stranicu (padajući meni)",
    jumpToPageInputLabel: "Skok na stranicu (unos)",
    lastPageLabel: "Zadnja stranica",
    listLabel: "Popis opcija",
    listView: "Prikaz u listi",
    moveAllToSource: "Pomakni sve na izvor",
    moveAllToTarget: "Pomakni sve na cilj",
    moveBottom: "Pomakni na dno",
    moveDown: "Pomakni dole",
    moveTop: "Pomakni na vrh",
    moveToSource: "Pomakni na izvor",
    moveToTarget: "Pomakni na cilj",
    moveUp: "Pomakni gore",
    navigation: "Navigacija",
    next: "Sledeće",
    nextPageLabel: "Sledeća stranica",
    nullLabel: "Nije odabrano",
    otpLabel: "Unesite jednokratnu lozinku {0}",
    pageLabel: "Stranica {page}",
    passwordHide: "Sakrij lozinku",
    passwordShow: "Pokaži lozinku",
    previous: "Prethodno",
    prevPageLabel: "Prethodna stranica",
    removeLabel: "Ukloniti",
    rotateLeft: "Rotiraj ulevo",
    rotateRight: "Rotiraj udesno",
    rowsPerPageLabel: "Redova po stranici",
    saveEdit: "Spremi promene",
    scrollTop: "Pomakni na vrh",
    selectAll: "Odabrane su sve stavke",
    selectLabel: "Izaberi",
    selectRow: "Red odabran",
    showFilterMenu: "Prikaži meni filtra",
    slide: "Slajd",
    slideNumber: "Slajd {slideNumber}",
    star: "1 zvezda",
    stars: "Zvezda: {start}",
    trueLabel: "Da",
    unselectAll: "Poništen je odabir svih stavki",
    unselectLabel: "Poništi odabir",
    unselectRow: "Red neodabran",
    zoomImage: "Povećaj sliku",
    zoomIn: "Povećaj",
    zoomOut: "Smanji",
  },
};
